#!/usr/bin/env python3
# -!- encoding:utf8 -!-

from subprocess import getoutput

LOCALES = [
    'fr_FR'
]

def sanitize(s):
    return s.split('\n')[0].strip()

def create_picsou_h():
    status = sanitize(getoutput('git status --porcelain'))
    status = 'clean' if len(status) == 0 else 'dirty'

    commit = sanitize(getoutput('git rev-parse HEAD'))

    version = sanitize(getoutput('git describe --tags'))
    if len(version) == 0:
        version = 'dev'

    with open('picsou.h.dist') as f:
        data = f.read()

    data = data.replace('%{STATUS}%', status)
    data = data.replace('%{COMMIT}%', commit)
    data = data.replace('%{VERSION}%', version)

    with open('picsou.h', 'w') as f:
        f.write(data)

def release_translations():
    for locale in LOCALES:
        getoutput('lrelease translation/picsou_{0}.ts -qm translation/picsou_{0}.qm'.format(locale))

def main():
    create_picsou_h()
    release_translations()

if __name__ == '__main__':
    main()
