#!/usr/bin/env bash
#
# Exit as soon as an error occurs...
#
set -e
#
# Variables
#
BUILD_DIR="$(pwd)/build"
LIBGCRYPT="libgcrypt-1.8.4"
LIBGPGERROR="libgpg-error-1.33"
APT_DEPENDENCIES="mingw-w64-tools gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 gettext"
#
# Script
#
echo "Installing required packages..."
sudo apt install ${APT_DEPENDENCIES}
echo "Recreating a build directory..."
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
echo "Building ${LIBGPGERROR}..."
tar xjvf ${LIBGPGERROR}.tar.bz2
cd ${LIBGPGERROR}
./configure CFLAGS='-O3 -m64 -mtune=native -march=native' LDFLAGS='-s -static' --host=x86_64-w64-mingw32 --enable-threads=windows --prefix=${BUILD_DIR}
make -j4
make install
cd ..
echo "Building ${LIBGCRYPT}..."
tar xjvf ${LIBGCRYPT}.tar.bz2
cd ${LIBGCRYPT}
./configure CFLAGS='-O3 -m64 -mtune=native -march=native' LDFLAGS='-s -static' --host=x86_64-w64-mingw32 --enable-m-guard --with-gpg-error-prefix=${BUILD_DIR} --prefix=${BUILD_DIR}
make -j4
make install
cd ..
echo "Done."

